-- ============================================================================
-- LaptopCare Portal — reference schema + security policies
-- ----------------------------------------------------------------------------
-- This file is a REFERENCE for setting up a fresh Supabase project, or for
-- checking/upgrading an existing one. The app reads/writes the two tables
-- below using exactly these column names.
--
-- If your existing project already has these tables and working policies,
-- you do NOT need to re-run this file — the app is compatible either way.
--
-- How to use:
--   1. Supabase Dashboard -> SQL Editor -> paste & run the TABLES section.
--   2. Then run the POLICIES section (read the comments first — policies
--      replace whatever is currently configured for these tables).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABLES
-- ----------------------------------------------------------------------------
create table if not exists public.warranty_status (
  id                   bigint generated by default as identity primary key,
  serial_number        text not null,
  customer_name        text,
  status               text default 'Received',
  handover_date        date,
  estimated_completion date,
  notes                text,
  last_updated         timestamptz default now(),
  created_at           timestamptz default now()
);

create table if not exists public.service_status (
  id               bigint generated by default as identity primary key,
  serial_number    text not null,
  customer_name    text,
  phone_number     text,
  laptop_model     text,
  purchase_date    date,
  invoice_number   text,
  status           text default 'Processing',
  scheduled_date   date,
  service_end_date date,
  notes            text,
  last_updated     timestamptz default now(),
  created_at       timestamptz default now()
);

create index if not exists idx_warranty_serial  on public.warranty_status (lower(serial_number));
create index if not exists idx_service_serial   on public.service_status (lower(serial_number));
create index if not exists idx_warranty_status  on public.warranty_status (status);
create index if not exists idx_service_status   on public.service_status (status);

-- ----------------------------------------------------------------------------
-- ROW LEVEL SECURITY (recommended)
-- ----------------------------------------------------------------------------
-- The customer portal uses the public "anon" key and must be able to:
--   * read both tables            (serial-number lookups)
--   * insert into service_status  (booking form)
-- Staff on admin.html sign in through Supabase Auth, after which the SAME
-- client carries the staff user's JWT — the "authenticated" policies below
-- give signed-in staff full access to manage both tables.
-- ----------------------------------------------------------------------------
alter table public.warranty_status enable row level security;
alter table public.service_status  enable row level security;

-- ---- warranty_status --------------------------------------------------------
drop policy if exists "anon can view warranty"    on public.warranty_status;
drop policy if exists "staff full access warranty" on public.warranty_status;

create policy "anon can view warranty"
  on public.warranty_status for select
  to anon
  using (true);

create policy "staff full access warranty"
  on public.warranty_status for all
  to authenticated
  using (true)
  with check (true);

-- ---- service_status ---------------------------------------------------------
drop policy if exists "anon can view service"     on public.service_status;
drop policy if exists "anon can book service"     on public.service_status;
drop policy if exists "staff full access service" on public.service_status;

create policy "anon can view service"
  on public.service_status for select
  to anon
  using (true);

create policy "anon can book service"
  on public.service_status for insert
  to anon
  with check (true);

create policy "staff full access service"
  on public.service_status for all
  to authenticated
  using (true)
  with check (true);

-- ----------------------------------------------------------------------------
-- Optional: block junk bookings at the API layer
-- (mirrors the validation the portal already does client-side)
-- ----------------------------------------------------------------------------
create or replace function public.bookings_before_insert()
returns trigger language plpgsql as $$
begin
  if new.serial_number is null or trim(new.serial_number) = '' then
    raise exception 'serial_number is required';
  end if;
  return new;
end $$;

drop trigger if exists trg_bookings_before_insert on public.service_status;
create trigger trg_bookings_before_insert
  before insert on public.service_status
  for each row execute function public.bookings_before_insert();
